import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/common/PageHeader";
import { DataTable } from "@/components/common/DataTable";
import { transferOrders } from "@/lib/mock-data";
import { ClarifyNote } from "@/components/common/ClarifyNote";

export const Route = createFileRoute("/_app/transfer-orders")({
  head: () => ({ meta: [{ title: "Transfer Orders — HCTS" }] }),
  component: () => (
    <>
      <PageHeader title="Transfer Orders" description="Truck departures against dispatch notes (created on mobile)" />
      <div className="space-y-4 p-6">
        <ClarifyNote>
          Transfer Orders are generated by Loading Team mobile devices. Web portal is view / audit / report only.
        </ClarifyNote>
        <DataTable
          data={transferOrders}
          columns={[
            { key: "id", header: "Order #", className: "font-mono text-xs font-medium" },
            { key: "dispatchNote", header: "Dispatch Note", className: "font-mono text-xs" },
            { key: "truck", header: "Truck", className: "font-mono text-xs" },
            { key: "driver", header: "Driver" },
            { key: "provider", header: "Provider" },
            { key: "eta", header: "ETA", className: "tabular-nums" },
            { key: "status", header: "Status" },
          ]}
        />
      </div>
    </>
  ),
});
